routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Front\HomeController@index')->name('root');
Auth::routes();
Route::get('/camiones', 'Front\CamionesController@index')->name('front.camiones.index');
Route::get('/camiones/test', 'Front\CamionesController@show')->name('front.camiones.show');
Route::get('/buses', 'Front\BusesController@index')->name('front.buses.index');
Route::get('/buses/test', 'Front\BusesController@show')->name('front.buses.show');
Route::get('/utilitarios', 'Front\UtilitariosController@index')->name('front.utilitarios.index');
Route::get('/utilitarios/test', 'Front\UtilitariosController@show')->name('front.utilitarios.show');
Route::get('/noticias', 'Front\NoticiasController@index')->name('front.noticias.index');
Route::get('/noticias/test', 'Front\NoticiasController@show')->name('front.noticias.show');


Route::get('/contacto', 'Front\ContactController@index')->name('front.contacto.index');
Route::post('/contacto', 'Front\ContactController@store')->name('front.contacto.store');

Route::get('/searchTrucks', 'Front\CamionesController@search')->name('front.search.trucks');
Route::get('/searchBuses', 'Front\BusesController@search')->name('front.search.buses');
Route::get('/searchUtilities', 'Front\UtilitariosController@search')->name('front.search.utilities');

//Route::get('/nos-apoyan', 'Front\HomeController@nosapoyan')->name('front.nosapoyan');
//Route::get('/organizaciones-aliadas', 'Front\HomeController@aliados')->name('front.aliados');
//Route::get('/biblioteca', 'Front\HomeController@biblioteca')->name('front.biblioteca');
//Route::get('/events', 'Front\HomeController@events')->name('front.events');
//Route::get('/construccion', 'Front\HomeController@construction')->name('front.construction');

// Account Panel
Route::group(['prefix' => 'account', 'as' => 'account.', 'namespace' => 'Account', 'middleware' => ['auth', 'auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('listings', 'ListingsController');
    Route::resource('notifications', 'NotificationsController');
    Route::resource('messages', 'MessagesController');

    Route::get('vehicles/filter', 'VehicleController@filter');
    Route::resource('vehicles', 'VehicleController');
    Route::resource('file', 'FileController');

    Route::get('profile/show', [
		'as' => 'user.profile.show',
		'uses' => 'UserController@show'
	]);

	Route::patch('profile/update/{id}', [
		'as' => 'user.profile.update',
		'uses' => 'UserController@update'
	]);

});

// Admin Panel
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'auth.admin']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('users', 'UsersController');
//    Route::resource('activities', 'ActivitiesController');
//    Route::resource('actions', 'ActionsController');
//    Route::resource('habits', 'HabitsController');
//    Route::resource('notifications', 'NotificationsController');
//    Route::resource('messages', 'MessagesController');
});

resources/views/admin/layouts/alerts.blade.php
@if (!empty($alerts))
    <div class="alerts text-left">
        <!-- Validation Errors -->
        @foreach($alerts as $type => $messages)
            <div class="alert alert-{{$type}} alert-dismissable">
                @if (is_array($messages))
                    <ul>
                        @foreach($messages as $m)
                            <li>{{ $m }}</li>
                        @endforeach
                    </ul>
                @else
                    {{ $messages }}
                @endif
            </div>
        @endforeach
    </div>
@endif

resources/views/admin/layouts/nav.blade.php
<nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        {{--<a class="hidden-xs" style="display: inline-table; float: left;line-height: 55px; margin-left: 10px;">--}}
            {{--<img class="" src="/img/logo.png" height="30">--}}
        {{--</a>--}}
    </div>
    <ul class="nav navbar-top-links navbar-right pull-right">
        @if ($messages)
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#" aria-expanded="false">
                    <i class="fa fa-fw fa-envelope-o"></i>  <span class="label label-warning">{!! $messages->count() !!}</span>
                </a>
                <ul class="dropdown-menu dropdown-messages">
                    @foreach ($messages as $message)
                        <li class="">
                            <div class="dropdown-messages-box">
                                <div class="media-body">
                                    {!! $message->body !!}
                                    <small class="text-muted block">{!! $message->date_human !!} by {!! $message->author !!}</small>
                                </div>
                            </div>
                        </li>
                    @endforeach
                    <li class="no-padding">
                        <div class="no-margins text-right">
                            <a href="{!! route('admin.messages.index') !!}">
                                <strong>Read All</strong>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>
        @endif

        @if ($notifications)
            <li class="dropdown">
                <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#" aria-expanded="false">
                    <i class="fa fa-fw fa-globe"></i>  <span class="label label-warning">{!! $notifications->count() !!}</span>
                </a>
                <ul class="dropdown-menu dropdown-messages">
                    @foreach ($notifications as $notification)
                        <li class="">
                            <div class="dropdown-notifications-box">
                                <div class="media-body">
                                    {!! $notification->body !!}
                                    <small class="text-muted block">{!! $notification->date_human !!} by {!! $notification->author !!}</small>
                                </div>
                            </div>
                        </li>
                    @endforeach
                    <li class="no-padding">
                        <div class="no-margins text-right">
                            <a href="{!! route('admin.notifications.index') !!}">
                                <strong>Read All</strong>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>
        @endif

        <li>
            <a href="{{ url('auth/logout') }}" class="">
                Log out
                <i class="fa fa-power-off fa-fw m-l-xs"></i> <span class="hidden-xs"> {!! $first_name !!} </span>
            </a>
        </li>
    </ul>
</nav>

resources/views/admin/layouts/page.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta name="csrf-param" content="_token">

        <title> @yield('page_title') | Alianza Arboles </title>

        <link rel="stylesheet" href="{{ elixir('css/admin.css') }}">
        <link rel="stylesheet" href="{{ elixir('css/admin-theme.css') }}">
    </head>
    <body class="skin-3 mini-navbar">
        <div id="wrapper">
            <nav class="navbar-default navbar-static-side" role="navigation">
                <div class="sidebar-collapse">
                    @include('admin.layouts.sidebar')
                </div>
            </nav>

            <div id="page-wrapper" class="gray-bg">
                <div class="row border-bottom">
                    @include('admin.layouts.nav')
                </div>
                @if (view()->hasSection('breadcrumbs'))
                <div class="row wrapper border-bottom white-bg page-heading">
                    <div class="col-lg-12">
                        <h2>@yield('page_title')</h2>
                        @yield('breadcrumbs')
                    </div>
                </div>
                @endif
                <div class="wrapper wrapper-content animated fadeInUp">
                    @include('admin.layouts.alerts')
                    @yield('content')
                </div>
                <div class="footer">
                    <div>
                        <strong>Copyright</strong> PictureKeeper &copy; {{ date('Y') }}
                    </div>
                </div>
            </div>
        </div>

        <script  type="text/javascript" src="{{ elixir('js/admin.js') }}"></script>

        @yield('inline_scripts')
    </body>
</html>

resources/views/admin/layouts/sidebar.blade.php
<ul class="nav" id="side-menu">
    <li class="nav-header border-bottom">
        <div class="dropdown profile-element">
            <a href="{!! route('admin.home') !!}">
                <img alt="image" class="" src="/img/logo.jpg" height="38">
            </a>
            {{--<img src="/img/white-isologo.png" height="38">--}}
        </div>
        <div class="logo-element">
            <a href="{!! route('admin.home') !!}">
                <img src="/img/logo.jpg" height="50">
            </a>
        </div>
    </li>
    @foreach ($primary_menu as $menu)
        <li class="{{ (isset($menu['active']) and $menu['active']) ? 'active' : '' }}">
            @if (!isset($menu['items']))
                <a href="{{ $menu['link'] }}" {{ isset($menu['target']) && $menu['target'] ? ' target="' . $menu['target']. '"' : '' }}>
                    @if (isset($menu['icon']))<i class="fa fa-{{ $menu['icon'] }}"></i>@endif
                    <span class="nav-label">{{ $menu['title'] }}</span>
                </a>
            @else
                <a href="#">
                    <i class="fa fa-{{ $menu['icon'] }}"></i>
                    <span class="nav-label">{{$menu['title']}}</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav nav-second-level collapse">
                    @foreach ($menu['items'] as $item)
                        <li>
                            <a href="{{ $item['link'] }}">
                                @if (isset($item['icon']))<i class="fa fa-{{$item['icon']}} fa-fw"></i>@endif
                                {{$item['title']}}
                            </a>
                        </li>
                    @endforeach
                </ul>
            @endif
        </li>
    @endforeach
</ul>